### PR TITLE
Set check_interval, response_timeout, unhealthy_threshold and healthy_threshold as non-required with default values

### PR DESCRIPTION
**Pull request by tavsec**
## Description
In the description of Vultr Terraform provider, it says that `check_interval`, `response_timeout`, `unhealthy_threshold` and `healthy_threshold`in Health Check of Load Balancer are optional, with default values.
I updated the provider so it reflects the documentation.

### Checklist:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you linted your code locally prior to submission?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by optik-aper** [comment]
Instead of setting `Required: false` you should remove `Required` and use `Optional: true` per the TF error:
```terraform
╷
│ Error: Failed to load plugin schemas
│ 
│ Error while loading schemas for plugin components: Failed to obtain provider schema: Could not load the schema for provider
│ vultr.com/dev/vultr: provider vultr.com/dev/vultr has invalid schema for managed resource type "vultr_load_balancer", which is a
│ bug in the provider: "4 errors occurred:\n\t* health_check.check_interval: must set Optional, Required or Computed\n\t*
│ health_check.healthy_threshold: must set Optional, Required or Computed\n\t* health_check.response_timeout: must set Optional,
│ Required or Computed\n\t* health_check.unhealthy_threshold: must set Optional, Required or Computed\n\n"..
  ```

I tried it out like this:
```terraform
						"check_interval": {
							Type:         schema.TypeInt,
							Optional:     true,
							ValidateFunc: validation.IntBetween(1, 300),
							Default:      15,
						},
						"response_timeout": {
							Type:         schema.TypeInt,
							Optional:     true,
							ValidateFunc: validation.IntBetween(1, 300),
							Default:      5,
						},
						"unhealthy_threshold": {
							Type:         schema.TypeInt,
							Optional:     true,
							ValidateFunc: validation.IntBetween(1, 300),
							Default:      5,
						},
						"healthy_threshold": {
							Type:         schema.TypeInt,
							Optional:     true,
							ValidateFunc: validation.IntBetween(1, 300),
							Default:      5,
						},
```
If you can update the PR with that we'll gladly merge it in.  Thanks for the effort!

**Comment by tavsec** [comment]
Hey @optik-aper, thanks for reply, I updated the code and changed the fields from required to optional, as you said, in the latest commit.

**Comment by optik-aper** [comment]
@tavsec Thanks!  That looks good in my testing.

**Review by optik-aper — APPROVED** [review]
Tested and working.

**Comment by optik-aper** [comment]
@tavsec Thanks for fixing the `go fmt` quickly.  One last thing since we're already updating this schema.  There is a default from the API for the health check `path` as well.  Will you add:
```golang
						"path": {
							Type:     schema.TypeString,
							Optional: true,
							Default:  "/",
						},
```
That fixes the state diff when the option isn't provided upon subsequent `terraform apply`s after creation:
```terraform
 # vultr_load_balancer.foo will be updated in-place
  ~ resource "vultr_load_balancer" "foo" {
        id                  = "442418ad-3794-4da6-be83-d571f6a82469"
        # (10 unchanged attributes hidden)

      ~ health_check {
          - path                = "/" -> null
            # (6 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }

```

**Review by optik-aper — APPROVED** [review]
Working locally

**Comment by optik-aper** [comment]
@tavsec Thanks again!

**Pull request merged**
